### ISSUE TITLE
database not being created

### ISSUE THREAD

**Issue by asafbennatan** [juhaku/juhakudb#2]
11-12 12:51:36.129 16415-16415/com.example.asaf.doubleshoot E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.example.asaf.myapp, PID: 16415
                                                                              java.lang.RuntimeException: Unable to create application com.example.asaf.doubleshoot.application.MyApplication: android.database.sqlite.SQLiteException: near "$change": syntax error (code 1): , while compiling: CREATE TABLE IF NOT EXISTS test($change TEXT, _id INTEGER PRIMARY KEY, name TEXT, serial_number TEXT, serial_version_u_i_d INTEGER);
                                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4933)
                                                                                  at android.app.ActivityThread.access$1600(ActivityThread.java:180)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1536)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                  at android.os.Looper.loop(Looper.java:207)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5710)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
                                                                               Caused by: android.database.sqlite.SQLiteException: near "$change": syntax error (code 1): , while compiling: CREATE TABLE IF NOT EXISTS test($change TEXT, _id INTEGER PRIMARY KEY, name TEXT, serial_number TEXT, serial_version_u_i_d INTEGER);
                                                                                  at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                  at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:896)
                                                                                  at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:507)
                                                                                  at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                                  at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                                  at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                                  at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1704)
                                                                                  at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1635)
                                                                                  at db.juhaku.juhakudb.core.android.DatabaseHelper.onCreate(DatabaseHelper.java:78)
                                                                                  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
                                                                                  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                                  at db.juhaku.juhakudb.core.android.DatabaseHelper.getDb(DatabaseHelper.java:180)
                                                                                  at db.juhaku.juhakudb.core.android.EntityManager.executeTemplate(EntityManager.java:123)
                                                                                  at db.juhaku.juhakudb.core.android.EntityManager.fireStore(EntityManager.java:101)
                                                                                  at db.juhaku.juhakudb.core.android.EntityManager.store(EntityManager.java:84)
                                                                                  at db.juhaku.juhakudb.repository.android.SimpleAndroidRepository.store

**Comment by juhaku** [comment]
> Caused by: android.database.sqlite.SQLiteException: near "$change": syntax error (code 1): , while compiling: CREATE TABLE IF NOT EXISTS test($change TEXT, _id INTEGER PRIMARY KEY, name TEXT, serial_number TEXT, serial_version_u_i_d INTEGER);

Quoting the stacktrace. Android does not allow special characters as names of columns in tables. This library is not blocking illegal characters from names of tables nor columns.  I rather use just a-z letters in names. This error is coming from android and is not related to the libarary.
